### ISSUE TITLE
Great repo! Request to add more related works on Neural Fields Editing~ 

### ISSUE THREAD

**Issue by yuzewang1998** [EricLee0224/awesome-nerf-editing#2]
Hi, thanks for the great repo! Here are more related works on Neural Fields Editing.

 -  [CVPR 2021] [Neural Scene Graphs for Dynamic Scenes](https://openaccess.thecvf.com/content/CVPR2021/html/Ost_Neural_Scene_Graphs_for_Dynamic_Scenes_CVPR_2021_paper.html)
 -  [CVPR 2021] [NeuTex: Neural Texture Mapping for Volumetric Neural Rendering](https://openaccess.thecvf.com/content/CVPR2021/html/Xiang_NeuTex_Neural_Texture_Mapping_for_Volumetric_Neural_Rendering_CVPR_2021_paper.html)
 -  [CVPR 2021] [STaR: Self-supervised Tracking and Reconstruction of Rigid Objects in Motion with Neural Rendering](https://openaccess.thecvf.com/content/CVPR2021/html/Yuan_STaR_Self-Supervised_Tracking_and_Reconstruction_of_Rigid_Objects_in_Motion_CVPR_2021_paper.html)
 -  [CVPR 2022] [Self-supervised Neural Articulated Shape and Appearance Models](https://openaccess.thecvf.com/content/CVPR2022/html/Wei_Self-Supervised_Neural_Articulated_Shape_and_Appearance_Models_CVPR_2022_paper.html)
 -  ECCV 2022] [Multiview Regenerative Morphing with Dual Flows](https://link.springer.com/chapter/10.1007/978-3-031-19787-1_28)
 -  [NIPS 2022] [CageNeRF: Cage-based Neural Radiance Field for Generalized 3D Deformation and Animation](https://proceedings.neurips.cc/paper_files/paper/2022/hash/cb78e6b5246b03e0b82b4acc8b11cc21-Abstract-Conference.html)
 -  [TOG 2022] [SNeRF: Stylized Neural Implicit Representations for 3D Scenes](https://dl.acm.org/doi/abs/10.1145/3528223.3530107)
 -  [TOG 2022] [Neural rendering in a room: amodal 3D understanding and free-viewpoint rendering for the closed scene composed of pre-captured objects](https://dl.acm.org/doi/abs/10.1145/3528223.3530163)
 -  [WACV 2024] [3D Face Style Transfer with a Hybrid Solution of NeRF and Mesh Rasterization](https://openaccess.thecvf.com/content/WACV2024/html/Feng_3D_Face_Style_Transfer_With_a_Hybrid_Solution_of_NeRF_WACV_2024_paper.html)
 -  [arXiv] [UPST-NeRF: Universal Photorealistic Style Transfer of Neural Radiance Fields for 3D Scene](https://arxiv.org/abs/2208.07059)
 -  [arXiv] [Instant Neural Radiance Fields Stylization](https://arxiv.org/abs/2303.16884)
 -  [arXiv] [Appearance Editing with Free-viewpoint Neural Rendering](https://arxiv.org/abs/2110.07674)
 -  [arXiv] [DynVideo-E: Harnessing Dynamic NeRF for Large-Scale Motion- and View-Change Human-Centric Video Editing](https://arxiv.org/abs/2310.10624)
 -  [arXiv] [A General Implicit Framework for Fast NeRF Composition and Rendering](https://arxiv.org/abs/2308.04669)
 -  [arXiv] [LANe: Lighting-Aware Neural Fields for Compositional Scene Synthesis](https://arxiv.org/abs/2304.03280)
 -  [arXiv] [VolTeMorph: Realtime, Controllable and Generalisable Animation of Volumetric Representations](https://arxiv.org/abs/2208.00949)
 -  [arXiv] [Object-Centric Neural Scene Rendering](https://arxiv.org/abs/2012.08503)

**Comment by EricLee0224** [comment]
Hi Yuze,

Thanks for your contribution! We will consider your Supplementary list and make a update. 
One more thing is that we encourage you directly make a PR, so that you will automatically appear in the contributor list.
